CREATE TABLE SEDE (
    CODSEDE VARCHAR2 (30),
    NOMBRE VARCHAR2 (30),
    DIRECCION VARCHAR2 (30),
    CONSTRAINT pk_sede PRIMARY KEY (CodSede)
);

CREATE TABLE DEPARTAMENTO (
    CODDEP VARCHAR2 (30),
    NOMBRE VARCHAR2 (30);
    UBICACION VARCHAR2 (30),
    CODSEDE VARCHAR2 (30),
    CONSTRAINT pk_departamento  PRIMARY KEY(CODDEP, CODSEDE),
    CONSTRAINT fk_codSede FOREIGN KEY(CODSEDE) REFERENCES SEDE(CODSEDE)
);

CREATE TABLE PROGRAMADOR (
    SECUENCIA NUMBER (3),
    NOMBRE VARCHAR2 (20),
    APELLIDO1 VARCHAR2 (30),
    APELLIDO2 VARCHAR2 (30) NULL,
    DIRECCION VARCHAR2 (30),
    CUENTA NUMBER (24),
    TELEFONO NUMBER (9),
    TIPO VARCHAR2 (30),
    CODDEP VARCHAR2 (30),
    SECUENCIAMENTOR NUMBER(3),
    CONSTRAINT pk_programador PRIMARY KEY (SECUENCIA),
    CONSTRAINT fk_secuenciaMentor FOREIGN KEY (SECUENCIAMENTOR), REFERENCES PROGRAMADOR(SECUENCIA)
    CONSTRAINT fk_departamento FOREIGN KEY (CODSEDE, CODDEP),  REFERENCES DEPARTAMENTO (CODSEDE, CODDEP)
);

CREATE TABLE EQUIPO(
    CODEQUIPO NUMBER (5),
    DESCRIPCION VARCHAR2 (30),
    SECUENCIA NUMBER (3),
    CODSEDE VARCHAR2 (30),
    CODDEP VARCHAR2 (30),
    CONSTRAINT pk_equipo PRIMARY KEY (CODEQUIPO),
    CONSTRAINT fk_prog FOREIGN KEY (SECUENCIA, CODSEDE, CODDEP) REFERENCES PROGRAMADOR (SECUENCIA, CODSEDE, CODDEP)
);
CREATE TABLE EQUIPOPROG(
    SECUENCIA NUMBER (3),
    CODDEP VARCHAR2 (30),
    CODSEDE VARCHAR2 (30),
    CODEQUIPO NUMBER (5),
    CONSTRAINT pk_equipoprog PRIMARY KEY (SECUENCIA, CODDEP, CODSEDE, CODEQUIPO),
    CONSTRAINT fk_equipo FOREIGN KEY (CODEQUIPO) REFERENCES EQUIPO (CODEQUIPO),
    CONSTRAINT fk_equipo2 FOREIGN KEY (CODSEDE, CODDEP, SECUENCIA) REFERENCES PROGRAMADOR (CODEQUIPO, CODSEDE, CODDEP)
);

CREATE TABLE PROYECYO(
    FECHAINI DATE,
    DESCRIPCION VARCHAR2 (30),
    FECHAFIN DATE,
    CODEQUIPO NUMBER (5),
    PARTEPROY DATE,
    CONSTRAINT pk_proyecto PRIMARY KEY (FECHAINI, CODEQUIPO),
    CONSTRAINT fk_proyecto FOREIGN KEY (PARTEPROY) REFERENCES EQUIPO (FECHAINI),
    CONSTRAINT fk_equipo FOREIGN KEY (CODEQUIPO) REFERENCES EQUIPO (CODEQUIPO)
);